CREATE TABLE `client` (
  `uuid_client` CHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `uuid_business_group` CHAR(36) DEFAULT NULL,
  `database_name` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `client_name` varchar(255) COLLATE utf8mb4_bin NOT NULL,
  `host` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `port_bbdd` int DEFAULT NULL,
  `database_user_name` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `database_password` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `container_name` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `docker_volume_name` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `business_type` varchar(100) COLLATE utf8mb4_bin NOT NULL,
  `nif_cif` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL,
  `foundation_date` date DEFAULT NULL,
  `fiscal_address` varchar(255) COLLATE utf8mb4_bin NOT NULL,
  `physical_address` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `city` varchar(100) COLLATE utf8mb4_bin NOT NULL,
  `country` varchar(100) COLLATE utf8mb4_bin NOT NULL,
  `postal_code` varchar(20) COLLATE utf8mb4_bin NOT NULL,
  `company_phone` varchar(20) COLLATE utf8mb4_bin NOT NULL,
  `company_email` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `number_of_employees` int DEFAULT NULL,
  `industry_sector` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL,
  `average_inventory_volume` decimal(10,2) DEFAULT NULL,
  `currency` varchar(10) COLLATE utf8mb4_bin DEFAULT NULL,
  `preferred_payment_methods` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `operation_hours` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `has_multiple_warehouses` tinyint(1) DEFAULT '0',
  `annual_sales_volume` decimal(15,2) DEFAULT NULL,
  `verification_token` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `verification_token_expires_at` datetime DEFAULT NULL,
  `is_verified` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`uuid_client`),
  FOREIGN KEY (`uuid_business_group`) REFERENCES `business_group` (`uuid_business_group`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
