# config/packages/doctrine.yaml
imports:
  - { resource: doctrine_main.yaml }
  - { resource: doctrine_clients.yaml }
doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    #server_version: '5.7' # Especifica tu versión de servidor de base de datos aquí

  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      User:
        is_bundle: false
        type: attribute
        dir: '%kernel.project_dir%/src/User/Domain/Entity'
        prefix: 'App\User\Domain\Entity'
        alias: User
      Client:
        is_bundle: false
        type: attribute
        dir: '%kernel.project_dir%/src/Client/Domain/Entity'
        prefix: 'App\Client\Domain\Entity'
        alias: Client
      # Puedes añadir más módulos aquí de la misma forma

when@test:
  doctrine:
    dbal:
      dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

framework:
  cache:
    pools:
      doctrine.result_cache_pool:
        adapter: cache.app
      doctrine.system_cache_pool:
        adapter: cache.system