doctrine_migrations:
  migrations_paths:
    'DoctrineMigrations\Main': '%kernel.project_dir%/migrations/Main'
    'DoctrineMigrations\Client': '%kernel.project_dir%/migrations/Client'
  storage:
    table_storage:
      table_name: migration_versions
  em: default
  services:
    'doctrine.migrations.configuration.client':
      migrations_paths:
        'DoctrineMigrations\Client': '%kernel.project_dir%/migrations/Client'
      connection: client
      em: client