doctrine:
  dbal:
    default_connection: main
    connections:
      main:
        url: '%env(resolve:DATABASE_URL)%'
      cron:
        url: '%env(resolve:CRON_DATABASE_URL)%'
  orm:
    default_entity_manager: main
    entity_managers:
      main:
        connection: main
        mappings:
          Main:
            is_bundle: false
            type: attribute
            dir: '%kernel.project_dir%/src/Entity/Main'
            prefix: 'App\Entity\Main'
            alias: Main
          Client:
            is_bundle: false
            type: attribute
            dir: '%kernel.project_dir%/src/Entity/Client'
            prefix: 'App\Entity\Client'
            alias: Client
      cron:
        connection: cron
        mappings:
          Cron:
            is_bundle: false
            type: attribute
            dir: '%kernel.project_dir%/src/Entity/Cron'
            prefix: 'App\Entity\Cron'
            alias: Cron
monolog:
  channels: ['doctrine']
  handlers:
    doctrine:
      type: stream
      path: '%kernel.logs_dir%/doctrine.sql.log'
      level: debug
      channels: ['doctrine']

  # Configuraciones específicas de entorno
when@test:
  doctrine:
    dbal:
      dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool
  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system