framework:
    messenger:
        failure_transport: failed
        transports:
            async:
                dsn: 'doctrine://main'
                options:
                    table_name: messenger_messages
            failed:
                dsn: 'doctrine://main'
                options:
                    table_name: messenger_failed_messages
        routing:
            'App\Message\CreateDockerContainerMessage': async
            'App\Event\MailSentEvent': async
# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
