# config/packages/monolog.yaml
monolog:
    channels:
        - deprecation
    # Esto aplica en todos los entornos (all):
    # Si necesitas más configuración global, agrégala aquí.

# ========== Entorno DEV ==========
when@dev:
    monolog:
        handlers:
            main:
                type: rotating_file
                # Archivo de logs en dev
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                max_files: 10
                # Excluimos algunos canales (por ejemplo, "!event", "!doctrine")
                channels: [ "!event", "!doctrine" ]

            console:
                type: console
                process_psr_3_messages: false
                channels: [ "!event", "!doctrine", "!console" ]

            # Handler para deprecaciones (opcional):
            deprecation:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
                level: notice
                channels: [ deprecation ]

# ========== Entorno TEST ==========
when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

# ========== Entorno PROD ==========
when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # Evitar consumir mucha memoria si hay spam de logs
            nested:
                type: stream
                path: "php://stderr"
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: "php://stderr"
                formatter: monolog.formatter.json
