<?php

namespace DoctrineProxies\__CG__\App\Entity\Client;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product extends \App\Entity\Client\Product implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'cost_price' => [parent::class, 'cost_price', null],
        "\0".parent::class."\0".'datehourCreation' => [parent::class, 'datehourCreation', null],
        "\0".parent::class."\0".'datehourModification' => [parent::class, 'datehourModification', null],
        "\0".parent::class."\0".'days_average_consumption' => [parent::class, 'days_average_consumption', null],
        "\0".parent::class."\0".'days_serve_order' => [parent::class, 'days_serve_order', null],
        "\0".parent::class."\0".'ean' => [parent::class, 'ean', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'main_unit' => [parent::class, 'main_unit', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'name_unit1' => [parent::class, 'name_unit1', null],
        "\0".parent::class."\0".'name_unit2' => [parent::class, 'name_unit2', null],
        "\0".parent::class."\0".'out_system_stock' => [parent::class, 'out_system_stock', null],
        "\0".parent::class."\0".'sale_price' => [parent::class, 'sale_price', null],
        "\0".parent::class."\0".'tare' => [parent::class, 'tare', null],
        "\0".parent::class."\0".'uuid' => [parent::class, 'uuid', null],
        "\0".parent::class."\0".'uuidUserCreation' => [parent::class, 'uuidUserCreation', null],
        "\0".parent::class."\0".'uuidUserModification' => [parent::class, 'uuidUserModification', null],
        "\0".parent::class."\0".'weight_range' => [parent::class, 'weight_range', null],
        "\0".parent::class."\0".'weight_unit1' => [parent::class, 'weight_unit1', null],
        "\0".parent::class."\0".'weight_unit2' => [parent::class, 'weight_unit2', null],
        'cost_price' => [parent::class, 'cost_price', null],
        'datehourCreation' => [parent::class, 'datehourCreation', null],
        'datehourModification' => [parent::class, 'datehourModification', null],
        'days_average_consumption' => [parent::class, 'days_average_consumption', null],
        'days_serve_order' => [parent::class, 'days_serve_order', null],
        'ean' => [parent::class, 'ean', null],
        'id' => [parent::class, 'id', null],
        'main_unit' => [parent::class, 'main_unit', null],
        'name' => [parent::class, 'name', null],
        'name_unit1' => [parent::class, 'name_unit1', null],
        'name_unit2' => [parent::class, 'name_unit2', null],
        'out_system_stock' => [parent::class, 'out_system_stock', null],
        'sale_price' => [parent::class, 'sale_price', null],
        'tare' => [parent::class, 'tare', null],
        'uuid' => [parent::class, 'uuid', null],
        'uuidUserCreation' => [parent::class, 'uuidUserCreation', null],
        'uuidUserModification' => [parent::class, 'uuidUserModification', null],
        'weight_range' => [parent::class, 'weight_range', null],
        'weight_unit1' => [parent::class, 'weight_unit1', null],
        'weight_unit2' => [parent::class, 'weight_unit2', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
