# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

parameters:

services:
    # Configuración predeterminada para autowire y autoconfigure
    _defaults:
        autowire: true
        autoconfigure: true

    # Autoload de los servicios de la aplicación
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # Configuración del LoginUseCase
    App\User\Application\LoginUseCase:
        arguments:
            $userRepository: '@App\User\Infrastructure\OutputPorts\UserRepositoryInterface'
            # Esta línea asegura que el password hasher sea inyectado automáticamente
            $passwordHasher: '@Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface'

    # Configura controladores para que sean públicos y tengan las etiquetas adecuadas
    App\User\Infrastructure\InputAdapters\:
        resource: '../src/User/Infrastructure/InputAdapters'
        tags: ['controller.service_arguments']
        public: true

    # Configura los servicios para el manejo de repositorios y tokens
    App\User\Infrastructure\OutputAdapters\UserRepository:
        arguments:
            $registry: '@doctrine' # Este debe ser un alias para ManagerRegistry si es que está configurado así
        tags:
            - { name: 'doctrine.repository_service' }

    App\User\Infrastructure\OutputAdapters\JWTTokenManager:
        arguments:
            - '%env(APP_SECRET)%'

    doctrine.migrations.configuration.client:
        class: Doctrine\Migrations\Configuration\Migration\ConfigurationArray
        arguments:
            - migrations_paths:
                  'DoctrineMigrations\Client': '%kernel.project_dir%/migrations/Client'
              connection: client
              em: client