CREATE TABLE product_snapshot (
    id INT AUTO_INCREMENT PRIMARY KEY,
    uuid_client CHAR(36) NOT NULL,
    product_id INT NOT NULL,
    product_name VARCHAR(50) NOT NULL,
    percentage DECIMAL(5, 2) NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
